;; Costumization
(setq custom-file (expand-file-name "custom.el" user-emacs-directory))
(setq org-file (expand-file-name "org.el" user-emacs-directory))
(setq python-file (expand-file-name "python.el" user-emacs-directory))
(setq js-file (expand-file-name "javascript.el" user-emacs-directory))
(setq go-file (expand-file-name "go.el" user-emacs-directory))
(setq git-file (expand-file-name "git.el" user-emacs-directory))
(setq tools-file (expand-file-name "tools.el" user-emacs-directory))


(when (file-exists-p custom-file)
  (load custom-file))
(when (file-exists-p org-file)
  (load org-file))
(when (file-exists-p python-file)
  (load python-file))
(when (file-exists-p js-file)
  (load js-file))
(when (file-exists-p go-file)
  (load go-file))
(when (file-exists-p git-file)
  (load git-file))
(when (file-exists-p tools-file)
  (load tools-file))
